services:

  db:
    image: postgres
    container_name: postgres
    restart: always
       
    
    environment:
      POSTGRES_USER: mindcard_user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: mindcard
      PGDATA: /home/mindcard_user/data
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
    driver: local
