import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  headerBlock: {
    backgroundColor: '#9FD7F9',
    width: '100%',
    paddingVertical: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  welcomeText: {
    fontSize: 24,
    fontFamily: 'MontserratAlternates',
    color: '#042D3F',
    marginTop: 0,
  },
  welcomeSubText: {
    fontSize: 24,
    fontFamily: 'MontserratAlternates',
    color: '#042D3F',
  },
  formBlock: {
    backgroundColor: '#EBF7FD',
    width: '100%',
    alignSelf: 'center',
    borderRadius: 0,
    padding: 45,
    marginTop: 0,
  },
  inputLabel: {
    fontSize: 16,
    fontFamily: 'Verdana',
    color: '#042D3F',
    marginBottom: 8,
    textAlign: 'center'
  },
  inputField: {
    fontSize: 14,
    fontFamily: 'Segoe UI',
    borderRadius: 12,
    padding: 12,
    marginBottom: 15,
    textAlign: 'center',
    textAlignVertical: 'center',
    backgroundColor: 'transparent',
    borderWidth: 0.8,
    borderColor: '#D0F9D2',
    includeFontPadding: false,
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 0,
  },
  inputFieldFocused: {
    backgroundColor: '#F8FCFF',
    borderColor: '#042D3F',
    borderWidth: 0.5,
    borderRadius: 12,
  },
  actionsBlock: {
    backgroundColor: '#EBF7FD',
    width: '100%',
    height: '100%',
    padding: 25,
    paddingTop: 50,
    marginTop: 0,
    alignItems: 'center',
  },
  linkButton: {
    width: '80%',
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
    backgroundColor: '#9FD7F9',
    borderWidth: 0.5,
    borderColor: '#D0F9D2',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center'
  },
  linkButtonText: {
    fontSize: 16,
    fontFamily: 'Verdana',
    color: '#042D3F',
    textAlign: 'center',
  },
  secondaryLinkButton: {
    marginTop: 0,
    backgroundColor: '#9FD7F9',
    borderWidth: 0.5,
    borderColor: '#D0F9D2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryLinkButtonText: {
    fontSize: 16,
    fontFamily: 'Verdana',
    color: '#042D3F',
    textAlign: 'center',
    borderColor: '#D0F9D2',
  },
  imageLogoName: {
    width: 165,
    height: 35,
    tintColor: '#FFFFFF',
  },
});